# -*- coding: utf-8 -*-
"""wattbot_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WHQKzZTuvi16BCsNBe-XjE8KUOu3GhI
"""
!pip install --upgrade accelerate transformers sentence-transformers
!pip install -q rank-bm25 faiss-cpu

import os
import json
import numpy as np
import torch
import pickle
import faiss
from pathlib import Path
from tqdm.auto import tqdm
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from google.colab import drive

# 1. Mount Google Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Setup Paths
PROJECT_ROOT = Path("/content/drive/MyDrive/NLP_teamproject")
OUTPUT_DIR = PROJECT_ROOT / "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Output Directory: {OUTPUT_DIR}")

# 3. Load Chunks
chunk_file = OUTPUT_DIR / "chunks.json"
if not chunk_file.exists():
    raise FileNotFoundError(f"chunks.json not found in {OUTPUT_DIR}")

with open(chunk_file, "r", encoding="utf-8") as f:
    chunks = json.load(f)

print(f"Loaded {len(chunks)} chunks")
chunk_texts = [chunk['text'] for chunk in chunks]

# 4. Build BM25 Index
print("\nBuilding BM25 Index...")
tokenized_chunks = [text.lower().split() for text in tqdm(chunk_texts)]
bm25 = BM25Okapi(tokenized_chunks)

with open(OUTPUT_DIR / "bm25_index.pkl", "wb") as f:
    pickle.dump(bm25, f)

# 5. Build Dense Index (FAISS)
print("\nBuilding Dense Index...")
model_name = "sentence-transformers/all-MiniLM-L6-v2"
embedding_model = SentenceTransformer(model_name)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
embedding_model = embedding_model.to(device)
print(f"Device: {device}")

embeddings = embedding_model.encode(
    chunk_texts,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

# Create FAISS Index
index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings.astype('float32'))

# Save Files
np.save(OUTPUT_DIR / "chunk_embeddings.npy", embeddings)
faiss.write_index(index, str(OUTPUT_DIR / "faiss_index.idx"))

# Save Config
retrieval_config = {
    "embedding_model": model_name,
    "num_chunks": len(chunks),
    "embedding_dim": embeddings.shape[1],
    "device": device
}
with open(OUTPUT_DIR / "retrieval_config.json", "w") as f:
    json.dump(retrieval_config, f, indent=2)

print("\nSTAGE 4 COMPLETE: All indexes saved.")

# 1. Install & Fix Dependencies
!pip install -q --upgrade bitsandbytes accelerate transformers sentence-transformers rank-bm25 faiss-cpu

import os
import json
import torch
import pickle
import faiss
import numpy as np
from pathlib import Path
from google.colab import drive
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sentence_transformers import SentenceTransformer

# 2. Mount Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

PROJECT_ROOT = Path("/content/drive/MyDrive/NLP_teamproject")
OUTPUT_DIR = PROJECT_ROOT / "outputs"

# 3. Load Resources
print("Loading resources...")
with open(OUTPUT_DIR / "retrieval_config.json", "r") as f:
    config = json.load(f)

with open(OUTPUT_DIR / "chunks.json", "r") as f:
    chunks = json.load(f)

with open(OUTPUT_DIR / "bm25_index.pkl", "rb") as f:
    bm25 = pickle.load(f)

index = faiss.read_index(str(OUTPUT_DIR / "faiss_index.idx"))

device = 'cuda' if torch.cuda.is_available() else 'cpu'
embedding_model = SentenceTransformer(config["embedding_model"]).to(device)

# 4. Retrieval Logic
def retrieve_hybrid(query, top_k=3, alpha=0.5):
    # BM25
    tokenized_query = query.lower().split()
    bm25_scores = bm25.get_scores(tokenized_query)

    # Dense
    query_emb = embedding_model.encode([query], normalize_embeddings=True)
    distances, indices = index.search(query_emb.astype('float32'), len(chunks))

    # Map dense scores
    dense_map = {idx: score for idx, score in zip(indices[0], distances[0])}
    dense_scores = [dense_map.get(i, 0) for i in range(len(chunks))]

    # Normalize & Fuse
    def norm(s):
        return (s - np.min(s)) / (np.max(s) - np.min(s) + 1e-6)

    hybrid_scores = norm(np.array(bm25_scores)) * alpha + norm(np.array(dense_scores)) * (1 - alpha)

    # Get Top K
    top_indices = np.argsort(hybrid_scores)[::-1][:top_k]
    return [chunks[i] for i in top_indices]

# 5. Load LLM (Qwen2.5-3B)
print("Loading LLM...")
model_id = "Qwen/Qwen2.5-3B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

# 6. Generate Function
def generate_answer(query):
    docs = retrieve_hybrid(query)
    context = "\n".join([f"Source: {d['source']}\nText: {d['text']}" for d in docs])

    messages = [
        {"role": "system", "content": "You are a technical assistant. Answer based on the context."},
        {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"}
    ]

    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(device)

    outputs = model.generate(
        inputs.input_ids,
        max_new_tokens=256,
        temperature=0.7,
        do_sample=True
    )

    response = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    return response.split("assistant\n")[-1].strip() # Extract only answer

# Test
print("\nTest Answer:", generate_answer("What is the impact of renewable energy?"))

import os
import shutil
import pandas as pd
from google.colab import files
from tqdm.auto import tqdm
from pathlib import Path

# Setup paths
PROJECT_ROOT = Path("/content/drive/MyDrive/NLP_teamproject")
OUTPUT_DIR = PROJECT_ROOT / "outputs"
TEST_FILE = PROJECT_ROOT / "test_Q.csv"

# 1. Check & Upload test_Q.csv
if not TEST_FILE.exists():
    print(f"File not found: {TEST_FILE}")
    print("Please upload 'test_Q.csv' now:")
    uploaded = files.upload()
    for filename in uploaded.keys():
        shutil.move(filename, TEST_FILE)
    print("Upload complete.")

# 2. Generate Submission
print(f"Reading {TEST_FILE}...")
df_test = pd.read_csv(TEST_FILE)

submission_data = []

print(f"Generating answers for {len(df_test)} questions...")

for _, row in tqdm(df_test.iterrows(), total=len(df_test)):
    q_id = row.get('id')
    question = row.get('question')

    answer = "is_blank"

    if pd.notna(question):
        try:
            # Call the LLM function defined in previous step
            generated_text = generate_answer(str(question))

            # Clean up response
            if generated_text and generated_text.strip():
                answer = generated_text.strip()

        except Exception as e:
            print(f"Error on ID {q_id}: {e}")

    submission_data.append({"id": q_id, "answer": answer})

# 3. Save
submission_df = pd.DataFrame(submission_data)
save_path = OUTPUT_DIR / "submission.csv"
submission_df.to_csv(save_path, index=False)

print("-" * 30)
print(f"Saved to: {save_path}")
print(submission_df.head())

import pandas as pd
import json
import re
import os
import torch
from tqdm.auto import tqdm
from pathlib import Path

# Setup Paths
PROJECT_ROOT = Path("/content/drive/MyDrive/NLP_teamproject")
OUTPUT_DIR = PROJECT_ROOT / "outputs"
TEST_FILE = PROJECT_ROOT / "test_Q.csv"
META_FILE = PROJECT_ROOT / "metadata.csv"

# ============================================================================
# 1. Load Metadata with Encoding Handling (Fix for UnicodeDecodeError)
# ============================================================================
print("Loading metadata...")
try:
    # UTF-8
    meta_df = pd.read_csv(META_FILE, encoding='utf-8')
except UnicodeDecodeError:
    print("⚠ UTF-8 failed, trying ISO-8859-1...")
    # ISO-8859-1 
    meta_df = pd.read_csv(META_FILE, encoding='ISO-8859-1')

# Create a dictionary: id -> url
id_to_url = dict(zip(meta_df['id'], meta_df['url']))
print(f"Metadata loaded: {len(meta_df)} rows")

# ============================================================================
# 2. Helper Functions
# ============================================================================
def get_clean_id(source_path):
    """Extracts ID from filename (e.g., 'data/amazon2023.pdf' -> 'amazon2023')"""
    base = os.path.basename(str(source_path))
    return os.path.splitext(base)[0]

def generate_final_response(query, target_unit):
    # Retrieve (Uses the function defined in previous stages)
    docs = retrieve_hybrid(query, top_k=3)

    context_pieces = []
    top_id = ""
    top_text = ""

    # Prioritize the top document for ID attribution
    if docs:
        top_doc = docs[0]
        top_id = get_clean_id(top_doc['source'])
        top_text = top_doc['text']

        for d in docs:
            pid = get_clean_id(d['source'])
            context_pieces.append(f"[Source: {pid}]\n{d['text']}")

    context_text = "\n\n".join(context_pieces)

    # Prompt
    system_prompt = """You are an expert power system assistant.
Your task is to extract the specific value for a given unit from the context.
Output STRICT JSON format:
{
    "answer_value": "extracted number or key term (use 'is_blank' if not found)",
    "explanation": "Brief justification (max 50 words) quoting the source."
}
"""

    user_prompt = f"""Context:
{context_text}

Question: {query}
Target Unit: {target_unit}

Instructions:
1. Find the answer that matches the unit '{target_unit}'.
2. If the answer is a number, output ONLY the number in 'answer_value'.
3. If the unit is 'is_blank', output the text answer.
"""

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]

    # Generate
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(device)

    outputs = model.generate(
        inputs.input_ids,
        max_new_tokens=150,
        temperature=0.1,
        do_sample=False
    )

    response_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    raw_answer = response_text.split("assistant\n")[-1].strip()

    # Parse JSON
    result = {
        "answer_value": "is_blank",
        "explanation": "Not found",
        "ref_id": str([top_id]) if top_id else "[]",
        "ref_url": str([id_to_url.get(top_id, "")]) if top_id else "[]",
        "supporting_materials": top_text
    }

    try:
        json_match = re.search(r'\{.*\}', raw_answer, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group(0))
            result["answer_value"] = str(parsed.get("answer_value", "is_blank"))
            result["explanation"] = str(parsed.get("explanation", ""))
    except:
        pass # Keep defaults if JSON fails

    return result

# ============================================================================
# 3. Main Processing Loop
# ============================================================================
if not TEST_FILE.exists():
    print(f"Error: {TEST_FILE} not found.")
else:
    df_test = pd.read_csv(TEST_FILE)
    print(f"Processing {len(df_test)} questions...")

    submission_data = []

    for _, row in tqdm(df_test.iterrows(), total=len(df_test)):
        q_id = row['id']
        question = row['question']
        unit = row['answer_unit'] 

        if pd.isna(unit):
            unit = "is_blank"

        # Generate
        resp = generate_final_response(str(question), str(unit))

        # Construct 'answer' column (Value + Unit)
        val = resp['answer_value']

        # Logic to combine value and unit correctly
        if val == "is_blank":
            full_answer = "is_blank"
        elif str(unit) == "is_blank" or pd.isna(unit):
            full_answer = val
        else:
            # Avoid double unit (e.g., "50 Hz Hz")
            if str(unit) in str(val):
                 full_answer = val
            else:
                 full_answer = f"{val} {unit}"

        entry = {
            "id": q_id,
            "question": question,
            "answer": full_answer,
            "answer_value": val,
            "answer_unit": unit,
            "ref_id": resp['ref_id'],
            "ref_url": resp['ref_url'],
            "supporting_materials": resp['supporting_materials'],
            "explanation": resp['explanation']
        }
        submission_data.append(entry)

    # 4. Save
    submit_df = pd.DataFrame(submission_data)

    # Ensure correct column order matching train_QA.csv
    cols = ['id', 'question', 'answer', 'answer_value', 'answer_unit',
            'ref_id', 'ref_url', 'supporting_materials', 'explanation']
    submit_df = submit_df[cols]

    save_path = OUTPUT_DIR / "submission_new.csv"
    submit_df.to_csv(save_path, index=False)

    print(f"\nSubmission file generated successfully!")
    print(f"Saved to: {save_path}")
    print("Preview:")
    print(submit_df.head(3))